# Generated by Django 3.1.1 on 2020-12-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='未取名', max_length=100, verbose_name='实例名称'),
        ),
    ]
