# Generated by Django 3.1.1 on 2020-12-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='html'),
        ),
    ]
