# Generated by Django 3.1.1 on 2020-12-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='code'),
        ),
    ]
