# Generated by Django 3.1.1 on 2020-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='收货人')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default=True, max_length=6, null=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=10, verbose_name='详细地址')),
                ('house', models.CharField(max_length=10, verbose_name='门牌号')),
                ('label', models.CharField(max_length=10, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
    ]
