# Generated by Django 3.1.1 on 2020-10-19 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='日期')),
                ('price', models.CharField(max_length=20, verbose_name='价格')),
                ('remarks', models.CharField(max_length=20, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '流水',
                'verbose_name_plural': '流水',
            },
        ),
    ]
