# Generated by Django 3.1.1 on 2020-10-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='curr_date',
        ),
    ]
