# Generated by Django 3.1.1 on 2020-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='not_money',
            field=models.PositiveIntegerField(default=0, verbose_name='非当日返校金额'),
        ),
        migrations.AlterField(
            model_name='config',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='当日返校金额'),
        ),
    ]
