# Generated by Django 3.1.1 on 2020-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20201113_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='当日返校价格'),
        ),
        migrations.AlterField(
            model_name='config',
            name='not_money',
            field=models.PositiveIntegerField(default=0, verbose_name='非当日返校价格'),
        ),
    ]
