# Generated by Django 3.1.1 on 2020-11-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='reviewer_name',
            field=models.CharField(default='', max_length=30, verbose_name='审核人姓名'),
        ),
    ]
