# Generated by Django 3.1.1 on 2020-10-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201024_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': ('用户',), 'verbose_name_plural': '用户'},
        ),
    ]
