# Generated by Django 3.1.1 on 2020-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201024_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='-', max_length=11, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='姓名'),
        ),
    ]
