# Generated by Django 3.1.1 on 2020-11-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201106_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='md5_password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
