# Generated by Django 3.1.1 on 2020-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201030_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='明文密码')),
                ('md5_password', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='加密密码')),
            ],
            options={
                'verbose_name': ('用户',),
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': ('管理员',), 'verbose_name_plural': '管理员'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
