# Generated by Django 3.1.1 on 2020-10-30 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201030_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': ('普通用户',), 'verbose_name_plural': '普通用户'},
        ),
        migrations.AddField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
    ]
