# Generated by Django 3.1.1 on 2020-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201030_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='md5_password',
            field=models.CharField(default='', max_length=32, verbose_name='加密密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='明文密码'),
        ),
    ]
