# Generated by Django 3.1.1 on 2020-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201031_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=32, verbose_name='明文密码'),
        ),
    ]
