# Generated by Django 3.1.1 on 2020-11-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201031_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='余额')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': ('用户资料',),
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
