# Generated by Django 3.1.1 on 2020-11-06 16:26

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=upload.models.directory_path, verbose_name='文件名称'),
        ),
    ]
