# Generated by Django 3.1.1 on 2020-10-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '待发货'), (4, '已完成')], verbose_name='状态')),
                ('number', models.CharField(max_length=32, verbose_name='订单号')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.userinfo', verbose_name='用户')),
            ],
        ),
    ]
