# Generated by Django 3.1.1 on 2020-10-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20201024_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gander',
            field=models.CharField(choices=[(0, '女'), (1, '男')], default=1, max_length=6, verbose_name='性别'),
        ),
    ]
