# Generated by Django 3.1.1 on 2020-11-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20201109_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentfavorrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='点赞时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='example.news', verbose_name='动态'),
        ),
        migrations.AlterField(
            model_name='commentfavorrecord',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorRecord', to='example.comment', verbose_name='动态'),
        ),
    ]
