# Generated by Django 3.1.1 on 2020-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20201025_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(0, '女'), (1, '男')], default='男', max_length=1, verbose_name='性别'),
        ),
    ]
