# Generated by Django 3.1.1 on 2020-10-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20201025_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '女'), ('F', '男')], default='1', max_length=1, verbose_name='性别'),
        ),
    ]
