# Generated by Django 3.1.1 on 2020-11-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_1200'),
        ('example', '0005_remove_comment_favor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='commentfavorrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
