# Generated by Django 3.1.1 on 2020-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_auto_20201025_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', '男'), ('M', '女')], default='F', max_length=1, verbose_name='性别'),
        ),
    ]
