# Generated by Django 3.1.1 on 2021-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='sum',
            field=models.FloatField(default=0, verbose_name='累计收益'),
        ),
    ]
