# Generated by Django 3.1.1 on 2021-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_profit_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='基金代号'),
        ),
        migrations.AddField(
            model_name='profit',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
