# Generated by Django 3.1.1 on 2021-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20210206_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='phone',
            field=models.CharField(max_length=256, null=True, verbose_name='手机号'),
        ),
    ]
