# Generated by Django 3.1.1 on 2021-02-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20210206_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'verbose_name': '基金配置', 'verbose_name_plural': '基金配置'},
        ),
    ]
