# Generated by Django 3.1.1 on 2021-02-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20210206_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='money',
            field=models.FloatField(default=0, verbose_name='买入金额'),
        ),
    ]
