# Generated by Django 3.1.1 on 2021-03-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_auto_20210206_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True, verbose_name='代号')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '所有基金',
                'verbose_name_plural': '所有基金',
            },
        ),
    ]
