# Generated by Django 3.1.1 on 2021-03-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_fundall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, verbose_name='日涨幅')),
                ('week', models.CharField(max_length=10, verbose_name='近一周')),
                ('one_month', models.CharField(max_length=10, verbose_name='近一月')),
                ('three_month', models.CharField(max_length=10, verbose_name='近三月')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fundall', verbose_name='代号')),
            ],
            options={
                'verbose_name': '数据排行',
                'verbose_name_plural': '数据排行',
            },
        ),
    ]
