# Generated by Django 3.1.1 on 2021-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='day',
            field=models.CharField(default=0, max_length=10, verbose_name='日涨幅'),
        ),
        migrations.AlterField(
            model_name='future',
            name='one_month',
            field=models.CharField(default=0, max_length=10, verbose_name='近一月'),
        ),
        migrations.AlterField(
            model_name='future',
            name='three_month',
            field=models.CharField(default=0, max_length=10, verbose_name='近三月'),
        ),
        migrations.AlterField(
            model_name='future',
            name='week',
            field=models.CharField(default=0, max_length=10, verbose_name='近一周'),
        ),
    ]
