# Generated by Django 3.1.1 on 2021-03-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_auto_20210315_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='day',
            field=models.FloatField(default=0, verbose_name='日涨幅'),
        ),
        migrations.AlterField(
            model_name='future',
            name='one_month',
            field=models.FloatField(default=0, verbose_name='近一月'),
        ),
        migrations.AlterField(
            model_name='future',
            name='three_month',
            field=models.FloatField(default=0, verbose_name='近三月'),
        ),
        migrations.AlterField(
            model_name='future',
            name='week',
            field=models.FloatField(default=0, verbose_name='近一周'),
        ),
    ]
