# Generated by Django 3.1.1 on 2021-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_auto_20210316_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundall',
            name='open',
            field=models.BooleanField(default=True, verbose_name='是否打开'),
        ),
    ]
