# Generated by Django 3.1.1 on 2021-03-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0011_fundall_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundall',
            old_name='open',
            new_name='status',
        ),
    ]
