# Generated by Django 3.1.1 on 2021-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0012_auto_20210316_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundall',
            name='top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
