# Generated by Django 3.1.1 on 2021-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0013_fundall_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='today',
            field=models.FloatField(default=0, verbose_name='今日估值'),
        ),
    ]
