# Generated by Django 3.1.1 on 2021-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0015_future_six_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, null=True, verbose_name='姓名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fund', models.ManyToManyField(blank=True, to='fund.Future', verbose_name='基金')),
            ],
            options={
                'verbose_name': '基金用户',
                'verbose_name_plural': '基金用户',
            },
        ),
    ]
