# Generated by Django 3.1.1 on 2021-03-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0016_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_time',
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fund', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fund.future', verbose_name='基金')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fund.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '基金用户',
                'verbose_name_plural': '基金用户',
            },
        ),
    ]
