# Generated by Django 3.1.1 on 2020-10-12 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20201013_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='留言时间'),
        ),
    ]
