# Generated by Django 3.1.1 on 2020-10-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20201013_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='textarea',
            field=models.CharField(max_length=200, verbose_name='留言内容'),
        ),
    ]
