# Generated by Django 3.1.1 on 2020-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='address',
            field=models.CharField(max_length=30, verbose_name='IP地址'),
        ),
    ]
