# Generated by Django 3.1.1 on 2020-11-02 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=100, verbose_name='姓名')),
                ('xh', models.CharField(max_length=100, verbose_name='学号')),
                ('xb', models.CharField(max_length=100, verbose_name='性别')),
                ('xy', models.CharField(max_length=100, verbose_name='学院')),
                ('zy', models.CharField(max_length=100, verbose_name='专业')),
                ('nj', models.CharField(max_length=100, verbose_name='年级')),
                ('phone', models.CharField(max_length=100, verbose_name='联系方式')),
                ('instructor', models.CharField(max_length=100, verbose_name='辅导员')),
                ('matter', models.TextField(max_length=200, verbose_name='出校事由')),
                ('lxsj', models.CharField(max_length=100, verbose_name='出校日期')),
                ('cxqs', models.CharField(max_length=100, verbose_name='出校起始时间')),
                ('cxjs', models.CharField(max_length=100, verbose_name='出校结束时间')),
                ('xingdong', models.CharField(max_length=100, verbose_name='出校行动轨迹')),
                ('guiji', models.BooleanField(verbose_name='轨迹')),
                ('fanxiao', models.BooleanField(verbose_name='返校')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
