# Generated by Django 3.1.1 on 2020-11-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fanxiao',
            field=models.BooleanField(blank=True, null=True, verbose_name='返校'),
        ),
        migrations.AlterField(
            model_name='info',
            name='guiji',
            field=models.BooleanField(blank=True, null=True, verbose_name='轨迹'),
        ),
    ]
