# Generated by Django 3.1.1 on 2020-11-06 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholl', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='examine',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholl.info', verbose_name='备案'),
        ),
    ]
