# Generated by Django 3.1.1 on 2020-11-02 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0002_auto_20201102_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='beian',
            field=models.CharField(default='', max_length=100, verbose_name='备案号'),
        ),
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='审核人姓名')),
                ('opinion', models.CharField(max_length=100, verbose_name='审核意见')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholl.info', verbose_name='备案')),
            ],
        ),
    ]
