# Generated by Django 3.1.1 on 2020-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0003_auto_20201106_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fanxiao',
            field=models.BooleanField(default=True, verbose_name='返校'),
        ),
        migrations.AlterField(
            model_name='info',
            name='guiji',
            field=models.BooleanField(default=True, verbose_name='轨迹'),
        ),
    ]
