# Generated by Django 3.1.1 on 2020-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0003_auto_20201102_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(choices=[('s1', '已备案'), ('s2', '已离校'), ('s3', '已返校')], default='s1', max_length=10, verbose_name='出校状态'),
        ),
    ]
