# Generated by Django 3.1.1 on 2020-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0004_auto_20201106_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='matter',
            field=models.TextField(help_text='出校事由', max_length=200, verbose_name='出校事由'),
        ),
    ]
