# Generated by Django 3.1.1 on 2020-11-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0004_info_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examine',
            options={'ordering': ['-id'], 'verbose_name': '审核记录', 'verbose_name_plural': '审核记录'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-id'], 'verbose_name': '备案记录', 'verbose_name_plural': '备案记录'},
        ),
    ]
