# Generated by Django 3.1.1 on 2020-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0005_auto_20201102_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='beian',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='info',
            name='cxjs',
            field=models.CharField(blank=True, max_length=100, verbose_name='出校结束时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='cxqs',
            field=models.CharField(blank=True, max_length=100, verbose_name='出校起始时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, verbose_name='辅导员'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lxsj',
            field=models.CharField(blank=True, max_length=100, verbose_name='出校日期'),
        ),
        migrations.AlterField(
            model_name='info',
            name='matter',
            field=models.TextField(blank=True, max_length=200, verbose_name='出校事由'),
        ),
        migrations.AlterField(
            model_name='info',
            name='nj',
            field=models.CharField(blank=True, max_length=100, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='info',
            name='xb',
            field=models.CharField(blank=True, max_length=100, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='info',
            name='xh',
            field=models.CharField(blank=True, max_length=100, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='info',
            name='xingdong',
            field=models.CharField(blank=True, max_length=100, verbose_name='出校行动轨迹'),
        ),
        migrations.AlterField(
            model_name='info',
            name='xm',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='xy',
            field=models.CharField(blank=True, max_length=100, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zy',
            field=models.CharField(blank=True, max_length=100, verbose_name='专业'),
        ),
    ]
