# Generated by Django 3.1.1 on 2020-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0006_auto_20201106_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '备案记录', 'verbose_name_plural': '备案记录'},
        ),
        migrations.AlterField(
            model_name='info',
            name='nj',
            field=models.CharField(default='', max_length=100, verbose_name='年级'),
        ),
    ]
