# Generated by Django 3.1.1 on 2020-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0007_auto_20201102_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.IntegerField(choices=[(1, '已备案'), (2, '已离校'), (3, '已返校')], default=1, verbose_name='出校状态'),
        ),
    ]
