# Generated by Django 3.1.1 on 2020-11-07 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_1200'),
        ('scholl', '0008_auto_20201107_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='充值金额')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='充值时间')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
            },
        ),
    ]
