# Generated by Django 3.1.1 on 2020-11-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_1200'),
        ('scholl', '0009_rrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rrecord',
            new_name='Record',
        ),
    ]
