# Generated by Django 3.1.1 on 2020-11-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0010_auto_20201107_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fxrq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='返校日期'),
        ),
    ]
