# Generated by Django 3.1.1 on 2020-11-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0011_info_fxrq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='lxsj',
            field=models.CharField(max_length=100, verbose_name='离校日期'),
        ),
        migrations.AlterField(
            model_name='info',
            name='nj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='年级'),
        ),
    ]
