# Generated by Django 3.1.1 on 2020-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0012_auto_20201114_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='fanxiao',
            field=models.BooleanField(default=True, verbose_name='当日返校'),
        ),
    ]
