# Generated by Django 3.1.1 on 2020-11-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholl', '0013_auto_20201114_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examine',
            options={'verbose_name': '审核记录', 'verbose_name_plural': '审核记录'},
        ),
    ]
